// Auto-generated by /add-amplifier — host-side container-config for the
// Amplifier provider. Returns env vars the agent container needs to reach
// amplifierd running on the host in ~/.nanoclaw-amp/.
//
// Pattern: mirror src/providers/codex.ts (the /add-codex skill).
// API: src/providers/provider-container-registry.ts exports
// `registerProviderContainerConfig(name, fn)`.

import {
  registerProviderContainerConfig,
  type ProviderContainerConfigFn,
} from './provider-container-registry.js';

const configFn: ProviderContainerConfigFn = (_ctx) => {
  const port = process.env.AMPLIFIERD_PORT || '8410';
  return {
    env: {
      AMPLIFIERD_URL: `http://host.docker.internal:${port}`,
      AMPLIFIER_DEFAULT_BUNDLE: 'nanoclaw-amp',
      NO_PROXY: 'host.docker.internal,localhost,127.0.0.1',
      no_proxy: 'host.docker.internal,localhost,127.0.0.1',
    },
  };
};

registerProviderContainerConfig('amplifier', configFn);
